credentials:
  usernames:
    leandric:
      email: leandro.silva@escolamobile.com.br
      logged_in: False # Will be managed automatically
      name: Leandro S. Silva
      password: $2b$12$FyG00HZFHzjo/V5GUS6GTO34EUGyzJ97RUR270wBOyVuhMI0FUVha # Will be hashed automatically
    global:
      email: global@gmail.com
      logged_in: False # Will be managed automatically
      name: Global
      password: $2b$12$RDAhO8z0IT8yiFOGMYRfVuqJRqXL1gQPTmFW7wa7aKY/ZCfLpkpIO # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com